/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

/**
 *
 * @author casas
 */
public class Game extends javax.swing.JPanel {

    Launcher parent;
    /**
     * Creates new form Carousel
     * @param _parent
     * @param _indexGrado
     * @param _indexGame
     */
    public Game(Launcher _parent ,int _indexGrado, int _indexGame) {
        initComponents();
        
        parent = _parent;
        parent.indexGrado = _indexGrado;
        parent.indexGame = _indexGame;
    }
    
    void UpdateInfo(int _indexGrado, int _indexGame)
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarruselPanel = new javax.swing.JPanel();
        Bolitas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flechaD = new javax.swing.JLabel();
        flechaIz = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DescripcionPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1440, 880));
        setMinimumSize(new java.awt.Dimension(1440, 880));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1440, 880));

        CarruselPanel.setMaximumSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setMinimumSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setOpaque(false);
        CarruselPanel.setPreferredSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bolitas.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/PuntoCarruselFilled.png"))); // NOI18N
        Bolitas.add(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        Bolitas.add(jLabel5);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        Bolitas.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        Bolitas.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/PuntoCarruselEmpty.png"))); // NOI18N
        Bolitas.add(jLabel8);

        CarruselPanel.add(Bolitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 180, 30));

        flechaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Flecha derecha.png"))); // NOI18N
        CarruselPanel.add(flechaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 30, 60));

        flechaIz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Flecha izquierda.png"))); // NOI18N
        CarruselPanel.add(flechaIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 30, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Miniaturas/Ascensor/Ascensor0.png"))); // NOI18N
        CarruselPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 880, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        CarruselPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 770, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        CarruselPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 770, 430));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Embarque y desembarque en helicoptero");
        jLabel9.setToolTipText("");
        CarruselPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 360, 40));

        DescripcionPanel.setMaximumSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setMinimumSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setOpaque(false);
        DescripcionPanel.setPreferredSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Comenzar.png"))); // NOI18N
        DescripcionPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, -1, 50));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("<html>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno  estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido  usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió </html>");
        DescripcionPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CarruselPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescripcionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CarruselPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DescripcionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bolitas;
    private javax.swing.JPanel CarruselPanel;
    private javax.swing.JPanel DescripcionPanel;
    private javax.swing.JLabel flechaD;
    private javax.swing.JLabel flechaIz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
