/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import java.awt.FlowLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;



/**
 *
 * @author casas
 */
public class Game extends javax.swing.JPanel {
    
    ArrayList<String> imagenes = new ArrayList();
    int index = 0;
    
    
    

    Launcher parent;
    /**
     * Creates new form Carousel
     * @param _parent
     * @param _indexGrado
     * @param _indexGame
     */
    public Game(Launcher _parent ,int _indexGrado, int _indexGame) {
        initComponents();            
        parent = _parent;
        parent.indexGrado = _indexGrado;
        parent.indexGame = _indexGame;
        initializeBolitas();
        UpdateBolitas();
    }
    
    private void initializeBolitas() {
        // Inicializar las bolitas como instancias de BolitaLlena
        Bolitas.setLayout(new FlowLayout());
        for (int i = 0; i < 5; i++) {
            BolitaLlena bolita = new BolitaLlena();
            Bolitas.add(bolita);
        }
    }

    
    void UpdateBolitas() {
    // Iterar sobre todas las bolitas y cambiar su imagen según la posición actual del carrusel
    for (int i = 0; i < 5; i++) {
        if (i == index) {
            ((BolitaLlena) Bolitas.getComponent(i)).setLlena(true);
        } else {
            ((BolitaLlena) Bolitas.getComponent(i)).setLlena(false);
        }
    }
    
    // Revalidar y repintar el panel Bolitas después de actualizar las bolitas
    Bolitas.revalidate();
    Bolitas.repaint();
}


    
    void UpdateInfo(int _indexGrado, int _indexGame)
    {
        
    }
        
    
    
    void UpdateArray (String nombreJuego){
        
        imagenes.clear();
        for (int i = 0; i < 5; i++) {
            imagenes.add("src/InterfazGame/Miniaturas/" + nombreJuego + "/" + nombreJuego + i + ".png");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarruselPanel = new javax.swing.JPanel();
        Bolitas = new javax.swing.JPanel();
        flechaD = new javax.swing.JLabel();
        flechaIz = new javax.swing.JLabel();
        imagenCarrusel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DescripcionPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1440, 880));
        setMinimumSize(new java.awt.Dimension(1440, 880));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1440, 880));

        CarruselPanel.setMaximumSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setMinimumSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setOpaque(false);
        CarruselPanel.setPreferredSize(new java.awt.Dimension(1440, 580));
        CarruselPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bolitas.setOpaque(false);
        CarruselPanel.add(Bolitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 180, 30));

        flechaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Flecha derecha.png"))); // NOI18N
        flechaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaDMouseClicked(evt);
            }
        });
        CarruselPanel.add(flechaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 30, 60));

        flechaIz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Flecha izquierda.png"))); // NOI18N
        flechaIz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaIzMouseClicked(evt);
            }
        });
        CarruselPanel.add(flechaIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 30, 80));

        imagenCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Miniaturas/Ascensor/Ascensor0.png"))); // NOI18N
        CarruselPanel.add(imagenCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 880, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        CarruselPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 770, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Cuadrado fondo enfocado.png"))); // NOI18N
        CarruselPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 770, 430));

        jLabel9.setFont(new java.awt.Font("Raleway Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Embarque y desembarque en helicoptero");
        jLabel9.setToolTipText("");
        CarruselPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 410, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Barrita aislada descripción.png"))); // NOI18N
        CarruselPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 10, 40));

        DescripcionPanel.setMaximumSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setMinimumSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setOpaque(false);
        DescripcionPanel.setPreferredSize(new java.awt.Dimension(1440, 300));
        DescripcionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGame/Comenzar.png"))); // NOI18N
        DescripcionPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, -1, 50));

        jLabel12.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("<html>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno  estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido  usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió </html>");
        DescripcionPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CarruselPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescripcionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CarruselPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DescripcionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flechaIzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaIzMouseClicked
                          
        index--;
        
        if(index < 0){
          index = 4;          
        }
        imagenCarrusel.setIcon(new ImageIcon(imagenes.get(index)));
        UpdateBolitas();   

        
        
    }//GEN-LAST:event_flechaIzMouseClicked

    private void flechaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaDMouseClicked
        
        index++;
        if(index > 4) {
            index = 0;
        }
        imagenCarrusel.setIcon(new ImageIcon(imagenes.get(index)));                
                
        UpdateBolitas();
        
        
    }//GEN-LAST:event_flechaDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bolitas;
    private javax.swing.JPanel CarruselPanel;
    private javax.swing.JPanel DescripcionPanel;
    private javax.swing.JLabel flechaD;
    private javax.swing.JLabel flechaIz;
    private javax.swing.JLabel imagenCarrusel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
