/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author FedericoGarciaBarrei
 */
public class Home extends javax.swing.JPanel {

    Launcher parent;
    ArrayList<String> imagenes = new ArrayList();
    
    /**
     * Creates new form Home
     * @param _parent
     * @param _indexGrado
     */
    public Home(Launcher _parent, int _indexGrado) throws IOException, JSONException {
        initComponents();
        System.out.print(UpdateInfo(_indexGrado));
        JSONArray juegos = UpdateInfo(_indexGrado);
        UpdateArray(juegos);
        this.NumeroGrado.setText("Grado número" + _indexGrado);

        parent = _parent;
        parent.indexGrado = _indexGrado;
    }
    
    
    JSONArray UpdateInfo(int _indexGrado) throws IOException, JSONException {
    try (BufferedReader br = new BufferedReader(new FileReader("src/DB.json"))) {
        StringBuilder sb = new StringBuilder();
        String line;
        while ((line = br.readLine()) != null) {
            sb.append(line);
        }
        JSONObject json = new JSONObject(sb.toString());
        JSONArray grados = json.getJSONArray("grados");
        return grados.getJSONObject(_indexGrado).getJSONArray("juegos");
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        return new JSONArray(); // Devuelve un JSONArray vacío en caso de error
    }
}

    
    void UpdateArray(JSONArray gradoArray) throws JSONException {
    for (int i = 0; i < 5; i++) {
        JSONObject juego = gradoArray.getJSONObject(i);
        String imagen = juego.getString("imagen");
        imagenes.add("src/InterfazHome/Miniaturas simuladores/" + imagen + ".png");
    }
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Helicop = new javax.swing.JLabel();
        Rcp = new javax.swing.JLabel();
        Fire = new javax.swing.JLabel();
        Robot = new javax.swing.JLabel();
        Grua = new javax.swing.JLabel();
        Bomberos = new javax.swing.JLabel();
        NumeroGrado = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 880));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(1400, 840));
        jPanel2.setMinimumSize(new java.awt.Dimension(1400, 840));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 840));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        Helicop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton0.png"))); // NOI18N
        Helicop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Helicop.setName(""); // NOI18N
        Helicop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelicopMouseClicked(evt);
            }
        });
        jPanel2.add(Helicop);

        Rcp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton1.png"))); // NOI18N
        Rcp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rcp.setName(""); // NOI18N
        Rcp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RcpMouseClicked(evt);
            }
        });
        jPanel2.add(Rcp);

        Fire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton2.png"))); // NOI18N
        Fire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fire.setName(""); // NOI18N
        Fire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FireMouseClicked(evt);
            }
        });
        jPanel2.add(Fire);

        Robot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton3.png"))); // NOI18N
        Robot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Robot.setName(""); // NOI18N
        Robot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RobotMouseClicked(evt);
            }
        });
        jPanel2.add(Robot);

        Grua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton4.png"))); // NOI18N
        Grua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grua.setName(""); // NOI18N
        Grua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GruaMouseClicked(evt);
            }
        });
        jPanel2.add(Grua);

        Bomberos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton5.png"))); // NOI18N
        Bomberos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bomberos.setName(""); // NOI18N
        Bomberos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BomberosMouseClicked(evt);
            }
        });
        jPanel2.add(Bomberos);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        NumeroGrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumeroGrado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NumeroGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 860, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HelicopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelicopMouseClicked
        parent.CrearNuevoGamePorIndice(parent.indexGrado,0);
    }//GEN-LAST:event_HelicopMouseClicked

    private void RcpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RcpMouseClicked
        parent.CrearNuevoGamePorIndice(parent.indexGrado,1);
    }//GEN-LAST:event_RcpMouseClicked

    private void FireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FireMouseClicked
         parent.CrearNuevoGamePorIndice(parent.indexGrado,2);
    }//GEN-LAST:event_FireMouseClicked

    private void RobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RobotMouseClicked
         parent.CrearNuevoGamePorIndice(parent.indexGrado,3);
    }//GEN-LAST:event_RobotMouseClicked

    private void GruaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruaMouseClicked
         parent.CrearNuevoGamePorIndice(parent.indexGrado,4);
    }//GEN-LAST:event_GruaMouseClicked

    private void BomberosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BomberosMouseClicked
         parent.CrearNuevoGamePorIndice(parent.indexGrado,5);
    }//GEN-LAST:event_BomberosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bomberos;
    private javax.swing.JLabel Fire;
    private javax.swing.JLabel Grua;
    private javax.swing.JLabel Helicop;
    private javax.swing.JLabel NumeroGrado;
    private javax.swing.JLabel Rcp;
    private javax.swing.JLabel Robot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
