/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

/**
 *
 * @author FedericoGarciaBarrei
 */
public class Home extends javax.swing.JPanel {

    Launcher parent;
    
    /**
     * Creates new form Home
     * @param _parent
     * @param _indexGrado
     */
    public Home(Launcher _parent, int _indexGrado) {
        initComponents();
        
        parent = _parent;
        parent.indexGrado = _indexGrado;
    }
    
    void UpdateInfo(int _indexGrado)
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Helicop = new javax.swing.JLabel();
        Rcp = new javax.swing.JLabel();
        Fire = new javax.swing.JLabel();
        Robot = new javax.swing.JLabel();
        Grua = new javax.swing.JLabel();
        Bomberos = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 880));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(1400, 840));
        jPanel2.setMinimumSize(new java.awt.Dimension(1400, 840));
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 840));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        Helicop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton0.png"))); // NOI18N
        Helicop.setName(""); // NOI18N
        Helicop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelicopMouseClicked(evt);
            }
        });
        jPanel2.add(Helicop);

        Rcp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton1.png"))); // NOI18N
        Rcp.setName(""); // NOI18N
        jPanel2.add(Rcp);

        Fire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton2.png"))); // NOI18N
        Fire.setName(""); // NOI18N
        jPanel2.add(Fire);

        Robot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton3.png"))); // NOI18N
        Robot.setName(""); // NOI18N
        jPanel2.add(Robot);

        Grua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton4.png"))); // NOI18N
        Grua.setName(""); // NOI18N
        jPanel2.add(Grua);

        Bomberos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazHome/Miniaturas simuladores/HomeButton5.png"))); // NOI18N
        Bomberos.setName(""); // NOI18N
        jPanel2.add(Bomberos);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HelicopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelicopMouseClicked
        parent.CrearNuevoGamePorIndice(parent.indexGrado,0);
    }//GEN-LAST:event_HelicopMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bomberos;
    private javax.swing.JLabel Fire;
    private javax.swing.JLabel Grua;
    private javax.swing.JLabel Helicop;
    private javax.swing.JLabel Rcp;
    private javax.swing.JLabel Robot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
